services:
  db:
    image: mysql:latest
    container_name: sampleshare_db
    restart: always
    volumes: 
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: 
      - .env

  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sampleshare_web
    command: >
      sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on: 
      - db
volumes:
  data:
