# Generated by Django 5.1.1 on 2024-10-16 01:57

import django.core.validators
import django.db.models.deletion
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatName', models.CharField(max_length=50)),
                ('chatTimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleName', models.CharField(max_length=50)),
                ('audioFile', models.FileField(upload_to='samples/', validators=[website.models.validate_length, django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('isPublic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField()),
                ('postTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('samples', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('messageTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('chats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.chat')),
                ('samples', models.ManyToManyField(to='website.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=50)),
                ('samples', models.ManyToManyField(null=True, to='website.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentMessage', models.TextField()),
                ('commentTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.post')),
                ('samples', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.sample')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('userPhoto', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(max_length=1000)),
                ('numberOfFollowers', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='userProfiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='userProfiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.userprofile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='userProfiles',
            field=models.ManyToManyField(null=True, to='website.userprofile'),
        ),
    ]
