# Generated by Django 5.1.1 on 2024-10-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='genre',
            name='samples',
            field=models.ManyToManyField(to='website.sample'),
        ),
    ]
