# Generated by Django 5.1.1 on 2024-10-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userPhoto',
            field=models.ImageField(blank=True, default='static/images/profile_picture_default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
