# Generated by Django 5.1.1 on 2024-10-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
