# Generated by Django 5.1.1 on 2024-10-14 04:33

import django.core.validators
import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userProfiles',
        ),
        migrations.AlterField(
            model_name='sample',
            name='audioFile',
            field=models.FileField(upload_to='samples/', validators=[website.models.validate_length, django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='post',
            name='userProfiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.userprofile'),
        ),
    ]
