# Generated by Django 4.2.16 on 2024-10-10 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_userprofile_email_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userProfiles',
        ),
        migrations.AddField(
            model_name='post',
            name='userProfiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.userprofile'),
        ),
    ]
