# Generated by Django 5.1.1 on 2024-10-14 04:47

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_post_userprofiles_alter_sample_audiofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='audioFile',
            field=models.FileField(upload_to='samples/', validators=[website.models.validate_length]),
        ),
    ]
