# Generated by Django 5.1.1 on 2024-10-14 04:55

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_sample_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='audioFile',
            field=models.FileField(upload_to='samples/', validators=[website.models.validate_length, django.core.validators.FileExtensionValidator(allowed_extensions=['mp3, wav'])]),
        ),
    ]
