# Generated by Django 5.1.1 on 2024-10-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_chat_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreName',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
