# Generated by Django 5.1.1 on 2024-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_sample_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
