# Generated by Django 4.2.16 on 2024-10-16 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_userprofile_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='samples',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.sample'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
